version: '3.7'

services:
  backend:
    platform: linux/amd64
    build: .
    ports:
      - '8000:8000'

  frontend:
    platform: linux/amd64
    build: ./client
    restart: always
    volumes:
      - './client/nginx:/etc/nginx/conf.d'
      - './backend/static:/static'
    ports:
      - '80:80'
    depends_on:
      - 'backend'

