version: '3'

services:
  backend:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - 'mariadb'

  frontend:
    build: ./client
    restart: always
    volumes:
      - './client/nginx:/etc/nginx/conf.d'
      - './backend/static:/static'
    ports:
      - '80:80'
    depends_on:
      - 'backend'

  mariadb:
    image: 'mariadb:10.6'
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: todo
      MYSQL_USER: whatsup
      MYSQL_PASSWORD: whatsuppw
    ports:
      - '3306:3306'
    volumes:
      - './.mariadb:/var/lib/mysql'
    restart: always
